export const brands = [
  "Keychron",
  "Logitech",
  "Razer",
  "Wooting"
];

export const keyboards = [
  {
    id: "wooting-80he",
    brand: "Wooting",
    name: "80HE",
    size: "80%",
    wireless: false,
    switchType: "Hall Effect / Magnetic",
    latency: "0.3–0.8 ms",
    battery: "Wired only",
    sound: "Sharp, gaming-focused",
    mount: "Gasket",
    material: "Plastic / Aluminum",
    polling: "8000 Hz",
    price: "$199+",
    image: "",
    productUrl: "https://wooting.io/wooting-80he"
  },
  {
    id: "wooting-60he-plus",
    brand: "Wooting",
    name: "60HE+",
    size: "60%",
    wireless: false,
    switchType: "Hall Effect / Magnetic",
    latency: "0.3–0.8 ms",
    battery: "Wired only",
    sound: "Sharp",
    mount: "Tray",
    material: "Plastic",
    polling: "8000 Hz",
    price: "$174+",
    image: "",
    productUrl: "https://wooting.io/wooting-60he"
  },
  {
    id: "razer-huntsman-v3-pro-tkl",
    brand: "Razer",
    name: "Huntsman V3 Pro TKL",
    size: "TKL",
    wireless: false,
    switchType: "Hall Effect / Analog",
    latency: "0.3 ms",
    battery: "Wired only",
    sound: "Sharp",
    mount: "Tray",
    material: "Plastic / Aluminum",
    polling: "8000 Hz",
    price: "$219+",
    image: "",
    productUrl: "https://www.razer.com/gb-en/gaming-keyboards/razer-huntsman-v3-pro-tenkeyless-8khz"
  },
  {
    id: "razer-huntsman-v3-pro-mini",
    brand: "Razer",
    name: "Huntsman V3 Pro Mini",
    size: "60%",
    wireless: false,
    switchType: "Hall Effect / Analog",
    latency: "0.3 ms",
    battery: "Wired only",
    sound: "Sharp",
    mount: "Tray",
    material: "Plastic",
    polling: "8000 Hz",
    price: "$179+",
    image: "",
    productUrl: "https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro-mini"
  },
  {
    id: "razer-huntsman-v3-pro",
    brand: "Razer",
    name: "Huntsman V3 Pro",
    size: "Full Size",
    wireless: false,
    switchType: "Hall Effect / Analog",
    latency: "0.3 ms",
    battery: "Wired only",
    sound: "Sharp",
    mount: "Tray",
    material: "Plastic / Aluminum",
    polling: "8000 Hz",
    price: "$249+",
    image: "",
    productUrl: "https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro"
  },
  {
    id: "razer-blackwidow-v4-75",
    brand: "Razer",
    name: "BlackWidow V4 75%",
    size: "75%",
    wireless: false,
    switchType: "Mechanical",
    latency: "1 ms",
    battery: "Wired only",
    sound: "Thocky",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$189+",
    image: "",
    productUrl: "https://www.razer.com/gaming-keyboards/razer-blackwidow-v4-75"
  },
  {
    id: "keychron-q1-max",
    brand: "Keychron",
    name: "Q1 Max",
    size: "75%",
    wireless: true,
    switchType: "Mechanical",
    latency: "2–4 ms",
    battery: "80 hrs",
    sound: "Poppy",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$209+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-q1-max-qmk-via-wireless-custom-mechanical-keyboard"
  },
  {
    id: "keychron-q2-max",
    brand: "Keychron",
    name: "Q2 Max",
    size: "65%",
    wireless: true,
    switchType: "Mechanical",
    latency: "2–4 ms",
    battery: "80 hrs",
    sound: "Deep",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$199+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-q2-max-qmk-via-wireless-custom-mechanical-keyboard"
  },
  {
    id: "keychron-q3-max",
    brand: "Keychron",
    name: "Q3 Max",
    size: "TKL",
    wireless: true,
    switchType: "Mechanical",
    latency: "2–4 ms",
    battery: "80 hrs",
    sound: "Deep",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$209+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-q3-max-qmk-via-wireless-custom-mechanical-keyboard"
  },
  {
    id: "keychron-q6-max",
    brand: "Keychron",
    name: "Q6 Max",
    size: "Full Size",
    wireless: true,
    switchType: "Mechanical",
    latency: "2–4 ms",
    battery: "80 hrs",
    sound: "Deep",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$229+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-q6-max-qmk-via-wireless-custom-mechanical-keyboard"
  },
  {
    id: "keychron-k2-he",
    brand: "Keychron",
    name: "K2 HE",
    size: "75%",
    wireless: true,
    switchType: "Hall Effect",
    latency: "1 ms",
    battery: "100 hrs",
    sound: "Muted",
    mount: "Tray",
    material: "Plastic / Aluminum",
    polling: "1000 Hz",
    price: "$139+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard"
  },
  {
    id: "keychron-q1-he",
    brand: "Keychron",
    name: "Q1 HE",
    size: "75%",
    wireless: true,
    switchType: "Hall Effect",
    latency: "1 ms",
    battery: "100 hrs",
    sound: "Muted",
    mount: "Gasket",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$219+",
    image: "",
    productUrl: "https://www.keychron.com/products/keychron-q1-he-qmk-wireless-custom-keyboard"
  },
  {
    id: "logitech-g-pro-x-tkl",
    brand: "Logitech",
    name: "G Pro X TKL",
    size: "TKL",
    wireless: true,
    switchType: "Mechanical",
    latency: "1 ms",
    battery: "50 hrs",
    sound: "Crisp",
    mount: "Tray",
    material: "Plastic",
    polling: "1000 Hz",
    price: "$199+",
    image: "",
    productUrl: "https://www.logitechg.com/en-gb/shop/p/pro-x-tkl-wireless-keyboard"
  },
  {
    id: "logitech-g915-x-lightspeed",
    brand: "Logitech",
    name: "G915 X Lightspeed",
    size: "Full Size",
    wireless: true,
    switchType: "Low Profile Mechanical",
    latency: "1 ms",
    battery: "36 hrs",
    sound: "Low-profile click",
    mount: "Tray",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$249+",
    image: "",
    productUrl: "https://www.logitechg.com/en-gb/shop/p/g915-x-wireless-mechanical-gaming-keyboard"
  },
  {
    id: "logitech-g915-x-tkl",
    brand: "Logitech",
    name: "G915 X TKL",
    size: "TKL",
    wireless: true,
    switchType: "Low Profile Mechanical",
    latency: "1 ms",
    battery: "36 hrs",
    sound: "Low-profile click",
    mount: "Tray",
    material: "Aluminum",
    polling: "1000 Hz",
    price: "$229+",
    image: "",
    productUrl: "https://www.logitechg.com/en-gb/shop/p/g915-x-tkl-wireless"
  }
];
