export const keyboards = [
  {
    "id": "logitech-g-pro-x-tkl",
    "brand": "Logitech",
    "name": "G Pro X TKL",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g-pro-x-tkl-rapid",
    "brand": "Logitech",
    "name": "G Pro X TKL Rapid",
    "size": "TKL",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Up to 50 hrs",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g915-x-lightspeed",
    "brand": "Logitech",
    "name": "G915 X Lightspeed",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g915-x-tkl",
    "brand": "Logitech",
    "name": "G915 X TKL",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g715",
    "brand": "Logitech",
    "name": "G715",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g713",
    "brand": "Logitech",
    "name": "G713",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g512",
    "brand": "Logitech",
    "name": "G512",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "logitech-g413-se",
    "brand": "Logitech",
    "name": "G413 SE",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-huntsman-v3-pro-mini",
    "brand": "Razer",
    "name": "Huntsman V3 Pro Mini",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "razer-huntsman-v3-pro-tkl",
    "brand": "Razer",
    "name": "Huntsman V3 Pro TKL",
    "size": "TKL",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "razer-huntsman-v3-pro",
    "brand": "Razer",
    "name": "Huntsman V3 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "razer-blackwidow-v4-75",
    "brand": "Razer",
    "name": "BlackWidow V4 75%",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-blackwidow-v4-pro-75",
    "brand": "Razer",
    "name": "BlackWidow V4 Pro 75%",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-blackwidow-v4-pro",
    "brand": "Razer",
    "name": "BlackWidow V4 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-blackwidow-v4-x",
    "brand": "Razer",
    "name": "BlackWidow V4 X",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-deathstalker-v2-pro",
    "brand": "Razer",
    "name": "DeathStalker V2 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Low-profile mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Low, crisp",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-deathstalker-v2-pro-tkl",
    "brand": "Razer",
    "name": "DeathStalker V2 Pro TKL",
    "size": "TKL",
    "wireless": false,
    "switchType": "Low-profile mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Low, crisp",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-deathstalker-v2",
    "brand": "Razer",
    "name": "DeathStalker V2",
    "size": "75%",
    "wireless": false,
    "switchType": "Low-profile mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Low, crisp",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "razer-ornata-v3",
    "brand": "Razer",
    "name": "Ornata V3",
    "size": "75%",
    "wireless": false,
    "switchType": "Mecha-membrane",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k70-max",
    "brand": "Corsair",
    "name": "K70 MAX",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k70-rgb-pro",
    "brand": "Corsair",
    "name": "K70 RGB Pro",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k70-core",
    "brand": "Corsair",
    "name": "K70 Core",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k70-pro-mini-wireless",
    "brand": "Corsair",
    "name": "K70 Pro Mini Wireless",
    "size": "60%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k65-plus-wireless",
    "brand": "Corsair",
    "name": "K65 Plus Wireless",
    "size": "65%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k65-rgb-mini",
    "brand": "Corsair",
    "name": "K65 RGB Mini",
    "size": "60%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k100-rgb",
    "brand": "Corsair",
    "name": "K100 RGB",
    "size": "Full-size",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "corsair-k55-rgb-pro",
    "brand": "Corsair",
    "name": "K55 RGB Pro",
    "size": "Full-size",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-pro-mini-wireless",
    "brand": "SteelSeries",
    "name": "Apex Pro Mini Wireless",
    "size": "60%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-pro-mini",
    "brand": "SteelSeries",
    "name": "Apex Pro Mini",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-pro-tkl-wireless-2023",
    "brand": "SteelSeries",
    "name": "Apex Pro TKL Wireless (2023)",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 50 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-pro-tkl-2023",
    "brand": "SteelSeries",
    "name": "Apex Pro TKL (2023)",
    "size": "TKL",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-pro",
    "brand": "SteelSeries",
    "name": "Apex Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-9-tkl",
    "brand": "SteelSeries",
    "name": "Apex 9 TKL",
    "size": "TKL",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "steelseries-apex-7",
    "brand": "SteelSeries",
    "name": "Apex 7",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-azoth-extreme",
    "brand": "ASUS",
    "name": "ROG Azoth Extreme",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-azoth",
    "brand": "ASUS",
    "name": "ROG Azoth",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-falchion-rx-low-profile",
    "brand": "ASUS",
    "name": "ROG Falchion RX Low Profile",
    "size": "75%",
    "wireless": false,
    "switchType": "Low-profile mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Low, crisp",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-falchion-ace-hfx",
    "brand": "ASUS",
    "name": "ROG Falchion Ace HFX",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-strix-scope-ii-96-wireless",
    "brand": "ASUS",
    "name": "ROG Strix Scope II 96 Wireless",
    "size": "96%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-strix-scope-ii-96",
    "brand": "ASUS",
    "name": "ROG Strix Scope II 96",
    "size": "96%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-rog-strix-scope-rx-tkl-wireless-deluxe",
    "brand": "ASUS",
    "name": "ROG Strix Scope RX TKL Wireless Deluxe",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "1.0\u20132.5 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "asus-tuf-gaming-k3-gen-ii",
    "brand": "ASUS",
    "name": "TUF Gaming K3 Gen II",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q1-max",
    "brand": "Keychron",
    "name": "Q1 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q2-max",
    "brand": "Keychron",
    "name": "Q2 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q3-max",
    "brand": "Keychron",
    "name": "Q3 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q5-max",
    "brand": "Keychron",
    "name": "Q5 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q6-max",
    "brand": "Keychron",
    "name": "Q6 Max",
    "size": "Full-size",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-q1-he",
    "brand": "Keychron",
    "name": "Q1 HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-k2-he",
    "brand": "Keychron",
    "name": "K2 HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-k2-max",
    "brand": "Keychron",
    "name": "K2 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-k8-max",
    "brand": "Keychron",
    "name": "K8 Max",
    "size": "TKL",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-v1-max",
    "brand": "Keychron",
    "name": "V1 Max",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-v6-max",
    "brand": "Keychron",
    "name": "V6 Max",
    "size": "Full-size",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "keychron-c3-pro",
    "brand": "Keychron",
    "name": "C3 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "wooting-80he",
    "brand": "Wooting",
    "name": "80HE",
    "size": "80%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "wooting-60he",
    "brand": "Wooting",
    "name": "60HE+",
    "size": "60%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "wooting-60he-module",
    "brand": "Wooting",
    "name": "60HE+ Module",
    "size": "60%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "wooting-two-he",
    "brand": "Wooting",
    "name": "Two HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "akko-mod-007b-he",
    "brand": "Akko",
    "name": "MOD 007B HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "akko-5075b-plus",
    "brand": "Akko",
    "name": "5075B Plus",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "akko-5075s-via",
    "brand": "Akko",
    "name": "5075S VIA",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "akko-monsgeek-fun60-max",
    "brand": "Akko",
    "name": "MonsGeek FUN60 Max",
    "size": "60%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "akko-mu01",
    "brand": "Akko",
    "name": "MU01",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "akko-spr67",
    "brand": "Akko",
    "name": "SPR67",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-air60-v2",
    "brand": "NuPhy",
    "name": "Air60 V2",
    "size": "60%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-air75-v2",
    "brand": "NuPhy",
    "name": "Air75 V2",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-air96-v2",
    "brand": "NuPhy",
    "name": "Air96 V2",
    "size": "96%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-halo65",
    "brand": "NuPhy",
    "name": "Halo65",
    "size": "65%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-halo75-v2",
    "brand": "NuPhy",
    "name": "Halo75 V2",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-gem80",
    "brand": "NuPhy",
    "name": "Gem80",
    "size": "80%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "nuphy-field75-he",
    "brand": "NuPhy",
    "name": "Field75 HE",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Up to 80 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-3-pro-he",
    "brand": "Glorious",
    "name": "GMMK 3 Pro HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-3-pro",
    "brand": "Glorious",
    "name": "GMMK 3 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-3-he",
    "brand": "Glorious",
    "name": "GMMK 3 HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Sharp, gaming-focused",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-3",
    "brand": "Glorious",
    "name": "GMMK 3",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-2-96",
    "brand": "Glorious",
    "name": "GMMK 2 96%",
    "size": "96%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "glorious-gmmk-2-compact",
    "brand": "Glorious",
    "name": "GMMK 2 Compact",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-one-3-mini",
    "brand": "Ducky",
    "name": "One 3 Mini",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-one-3-sf",
    "brand": "Ducky",
    "name": "One 3 SF",
    "size": "65%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-one-3-tkl",
    "brand": "Ducky",
    "name": "One 3 TKL",
    "size": "TKL",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-one-3-classic",
    "brand": "Ducky",
    "name": "One 3 Classic",
    "size": "Full-size",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-projectd-tinker-75",
    "brand": "Ducky",
    "name": "ProjectD Tinker 75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "ducky-origin-black-ducky-x-varmilo-miya-pro",
    "brand": "Ducky",
    "name": "Origin Black Ducky x Varmilo Miya Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-aula-f75",
    "brand": "Epomaker",
    "name": "Aula F75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-th80-pro-v2",
    "brand": "Epomaker",
    "name": "TH80 Pro V2",
    "size": "80%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-ek68",
    "brand": "Epomaker",
    "name": "EK68",
    "size": "65%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-rt100",
    "brand": "Epomaker",
    "name": "RT100",
    "size": "Full-size",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-p75",
    "brand": "Epomaker",
    "name": "P75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-x-aula-f99",
    "brand": "Epomaker",
    "name": "x Aula F99",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "epomaker-shadow-x",
    "brand": "Epomaker",
    "name": "Shadow-X",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-origins-60",
    "brand": "HyperX",
    "name": "Alloy Origins 60",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-origins-core",
    "brand": "HyperX",
    "name": "Alloy Origins Core",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-origins",
    "brand": "HyperX",
    "name": "Alloy Origins",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-rise",
    "brand": "HyperX",
    "name": "Alloy Rise",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-rise-75",
    "brand": "HyperX",
    "name": "Alloy Rise 75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "hyperx-alloy-core-rgb",
    "brand": "HyperX",
    "name": "Alloy Core RGB",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-rk61",
    "brand": "Royal Kludge",
    "name": "RK61",
    "size": "60%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-rk68",
    "brand": "Royal Kludge",
    "name": "RK68",
    "size": "65%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-rk84",
    "brand": "Royal Kludge",
    "name": "RK84",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-rk87",
    "brand": "Royal Kludge",
    "name": "RK87",
    "size": "TKL",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-rk96",
    "brand": "Royal Kludge",
    "name": "RK96",
    "size": "96%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 80 hrs",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-s98",
    "brand": "Royal Kludge",
    "name": "S98",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "royal-kludge-m75",
    "brand": "Royal Kludge",
    "name": "M75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "cooler-master-ck720",
    "brand": "Cooler Master",
    "name": "CK720",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "cooler-master-ck721",
    "brand": "Cooler Master",
    "name": "CK721",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "cooler-master-ck352",
    "brand": "Cooler Master",
    "name": "CK352",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "cooler-master-sk620",
    "brand": "Cooler Master",
    "name": "SK620",
    "size": "75%",
    "wireless": false,
    "switchType": "Low-profile mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "cooler-master-mk770",
    "brand": "Cooler Master",
    "name": "MK770",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "monsgeek-m1w-v3",
    "brand": "MonsGeek",
    "name": "M1W V3",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "monsgeek-m1-v5",
    "brand": "MonsGeek",
    "name": "M1 V5",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "monsgeek-m7w",
    "brand": "MonsGeek",
    "name": "M7W",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "monsgeek-m5w",
    "brand": "MonsGeek",
    "name": "M5W",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "monsgeek-fun60-pro",
    "brand": "MonsGeek",
    "name": "FUN60 Pro",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "lemokey-p1-pro",
    "brand": "Lemokey",
    "name": "P1 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "lemokey-p1-he",
    "brand": "Lemokey",
    "name": "P1 HE",
    "size": "75%",
    "wireless": false,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "lemokey-l1",
    "brand": "Lemokey",
    "name": "L1",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "lemokey-l3",
    "brand": "Lemokey",
    "name": "L3",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "lemokey-x1",
    "brand": "Lemokey",
    "name": "X1",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Full, poppy",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "drunkdeer-g60",
    "brand": "DrunkDeer",
    "name": "G60",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "drunkdeer-a75-pro",
    "brand": "DrunkDeer",
    "name": "A75 Pro",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "drunkdeer-a75-ultra",
    "brand": "DrunkDeer",
    "name": "A75 Ultra",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "drunkdeer-a75-master",
    "brand": "DrunkDeer",
    "name": "A75 Master",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "drunkdeer-g65",
    "brand": "DrunkDeer",
    "name": "G65",
    "size": "65%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Tray / gaming",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-tk68",
    "brand": "Gamakay",
    "name": "TK68",
    "size": "65%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-tk75",
    "brand": "Gamakay",
    "name": "TK75",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-tk75-he",
    "brand": "Gamakay",
    "name": "TK75 HE",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Up to 70 hrs",
    "sound": "Sharp, gaming-focused",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-lk67",
    "brand": "Gamakay",
    "name": "LK67",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-sn75",
    "brand": "Gamakay",
    "name": "SN75",
    "size": "75%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gamakay-k61-pro",
    "brand": "Gamakay",
    "name": "K61 Pro",
    "size": "60%",
    "wireless": false,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Wired only",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Plastic / aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-k1",
    "brand": "GravaStar",
    "name": "Mercury K1",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-k1-pro",
    "brand": "GravaStar",
    "name": "Mercury K1 Pro",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-k1-lite",
    "brand": "GravaStar",
    "name": "Mercury K1 Lite",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-v75",
    "brand": "GravaStar",
    "name": "Mercury V75",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-v75-pro",
    "brand": "GravaStar",
    "name": "Mercury V75 Pro",
    "size": "75%",
    "wireless": true,
    "switchType": "Mechanical",
    "latency": "2.0\u20134.0 ms",
    "battery": "Up to 70 hrs",
    "sound": "Balanced",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "1000 Hz",
    "price": "$\u2014"
  },
  {
    "id": "gravastar-mercury-v75-he",
    "brand": "GravaStar",
    "name": "Mercury V75 HE",
    "size": "75%",
    "wireless": true,
    "switchType": "Hall Effect / Magnetic",
    "latency": "0.3\u20130.8 ms",
    "battery": "Up to 70 hrs",
    "sound": "Sharp, gaming-focused",
    "mount": "Gasket / custom-style",
    "material": "Aluminum",
    "polling": "8000 Hz / high-speed",
    "price": "$\u2014"
  }
];

export const brands = [
  "ASUS",
  "Akko",
  "Cooler Master",
  "Corsair",
  "DrunkDeer",
  "Ducky",
  "Epomaker",
  "Gamakay",
  "Glorious",
  "GravaStar",
  "HyperX",
  "Keychron",
  "Lemokey",
  "Logitech",
  "MonsGeek",
  "NuPhy",
  "Razer",
  "Royal Kludge",
  "SteelSeries",
  "Wooting"
];
